feat: Slash Command Permissions
harmonyland/harmony pull request #151
Opened 2021-05-09 04:52 UTC by DjDeveloperr

2021-05-09 05:29 UTC, Helloyunho requested changes

2021-05-09 14:33 UTC, minseo0388 requested changes
approve except slashCommand.ts

2021-05-10 13:07 UTC, Helloyunho approved these changes
LGTM!

2021-05-10 14:08 UTC, minseo0388 approved these changes
approve

2021-05-12 07:09 UTC, merged