Code clean up
harmonyland/harmony pull request #159
Opened 2021-05-12 09:23 UTC by ZiomaleQ

## About

This pul request is mostly about code fixes. Like styling code, logic, and similar stuff

## Status

- [x] These changes have been tested against Discord API or contain no API change.
- [ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

2021-05-12 19:33 UTC, ZiomaleQ commented
In the last commit, ( [Link](https://github.com/harmonyland/harmony/pull/159/commits/389baf575b58477a5aca3e0a11408787919106f8) ) i missed all the message related events and gateway/mod.ts, I'm too scared to modify them in any way tbh

2021-05-30 11:55 UTC, DjDeveloperr requested changes

2021-05-30 11:55 UTC, DjDeveloperr commented on src/cache/default.ts
> +      setTimeout(cache.delete, expire, key)
Use arrow function here

2021-05-30 11:55 UTC, DjDeveloperr commented on src/client/client.ts
> +    this.presence = presence instanceof ClientPresence ? this.presence : new ClientPresence(presence)
You what

2021-05-30 11:55 UTC, DjDeveloperr commented on src/client/client.ts
> +      this.rest.get(INVITE(id)).then(
Maybe don't use Promises here but just async/await?

2021-05-30 11:55 UTC, DjDeveloperr commented on src/commands/client.ts
> +    this.on('messageCreate', async (msg: Message) => await this.processMessage(msg))
Maybe call it when processing event itself instead of adding listener? (in `src/gateway/handlers/messageCreate.ts`)

2021-05-30 11:55 UTC, DjDeveloperr commented on src/commands/client.ts
> +    const category = this.categories.get(command.category ?? "")
Imagine category with name `""`

2021-05-30 11:55 UTC, DjDeveloperr commented on src/gateway/handlers/applicationCommandCreate.ts
> +  const guild = await gateway.client.guilds.get(d.guild_id ?? "")
It will make unnecessary cache request. Imagine user having some custom cache over network.

2021-07-10 17:28 UTC, ZiomaleQ commented
I completely forgot about it. I'll finish it as fast as I can!

2021-07-10 18:07 UTC, ZiomaleQ commented on src/cache/default.ts
> +      setTimeout(cache.delete, expire, key)
As of merge, it's resolved.

2021-07-10 18:09 UTC, ZiomaleQ commented
Since lib changed I'd like to know what else should I change to match the standards of Harmony, or just close the pull request with no changes to lib at all.

2021-07-15 10:47 UTC, DjDeveloperr commented
> 
> 
> Since lib changed I'd like to know what else should I change to match the standards of Harmony, or just close the pull request with no changes to lib at all.

There haven't been so drastic changes in code or even _standards_, so I'm not sure what you mean.

2021-07-15 10:48 UTC, closed without merging

2021-07-15 11:03 UTC, DjDeveloperr commented
Why close the PR without any message? I'd like to clarify review was done, it was only left for you to resolve the requested changes. 😕