feat: team
harmonyland/harmony pull request #174
Opened 2021-06-07 10:20 UTC by kiki7000

## About
Added [team](https://discord.com/developers/docs/topics/teams#data-models-team-object) to harmony

## Status

- [x] These changes have been tested against Discord API or do not contain API change.
- [ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

2021-06-07 10:28 UTC, DjDeveloperr requested changes
LGTM 🎉 , some nits

2021-06-07 10:28 UTC, DjDeveloperr commented on src/types/team.ts
> +  membership_state: number
Please use enum here, https://discord.com/developers/docs/topics/teams#data-models-membership-state-enum

2021-06-07 10:28 UTC, DjDeveloperr commented on src/structures/application.ts
> +  team: Team | null
I'd prefer undefined over null here

2021-06-07 11:36 UTC, kiki7000 commented
Resolved

2021-06-07 11:38 UTC, DjDeveloperr requested changes

2021-06-07 11:38 UTC, DjDeveloperr commented on src/structures/team.ts
> +    this.owner = this.members.filter(member => member.id === data.owner_user_id)[0]
.find would be better here

2021-06-07 12:39 UTC, DjDeveloperr requested changes

2021-06-07 12:39 UTC, DjDeveloperr commented on src/structures/application.ts
> +    this.team = data.team ? new Team(client, data.team) : undefined
Please fix lint error here so we can land this PR

2021-06-08 12:40 UTC, DjDeveloperr approved these changes
LGTM, thanks!

2021-06-08 12:40 UTC, merged